// CT-15: Deploy orchestrator for all five Soroban contracts
// Deploys in dependency order and writes contract IDs to .env.contracts

import { execSync } from "child_process";
import { writeFileSync, appendFileSync } from "fs";

const NETWORK = process.env.STELLAR_NETWORK ?? "testnet";
const SOURCE = process.env.STELLAR_SOURCE_ACCOUNT ?? "default";
const CONTRACTS_DIR = process.env.CONTRACTS_DIR ?? "./opsr/contracts";
const ENV_OUT = ".env.contracts";

interface DeployedContract {
  name: string;
  id: string;
}

function deploySoroban(wasmPath: string): string {
  const result = execSync(
    `stellar contract deploy --wasm ${wasmPath} --source ${SOURCE} --network ${NETWORK}`,
    { encoding: "utf8" }
  ).trim();
  return result;
}

function invoke(contractId: string, fn: string, args: string): void {
  execSync(
    `stellar contract invoke --id ${contractId} --source ${SOURCE} --network ${NETWORK} -- ${fn} ${args}`,
    { stdio: "inherit" }
  );
}

async function main(): Promise<void> {
  writeFileSync(ENV_OUT, "# Auto-generated by deploy.ts\n");
  const deployed: Record<string, string> = {};

  const order: Array<{ name: string; wasm: string }> = [
    { name: "IDENTITY", wasm: `${CONTRACTS_DIR}/identity/identity.wasm` },
    { name: "REPUTATION", wasm: `${CONTRACTS_DIR}/reputation/reputation.wasm` },
    { name: "ESCROW", wasm: `${CONTRACTS_DIR}/escrow/escrow.wasm` },
    { name: "DOCUMENT", wasm: `${CONTRACTS_DIR}/document/document.wasm` },
    { name: "SHIPMENT", wasm: `${CONTRACTS_DIR}/shipment/shipment.wasm` },
  ];

  for (const { name, wasm } of order) {
    console.log(`Deploying ${name}...`);
    const id = deploySoroban(wasm);
    deployed[name] = id;
    appendFileSync(ENV_OUT, `${name}_CONTRACT_ID=${id}\n`);
    console.log(`  ${name} => ${id}`);
  }

  // Wire cross-contract addresses
  invoke(deployed.REPUTATION, "initialize", `--identity_contract ${deployed.IDENTITY}`);
  invoke(deployed.ESCROW, "initialize", `--identity_contract ${deployed.IDENTITY}`);
  invoke(deployed.DOCUMENT, "initialize", `--identity_contract ${deployed.IDENTITY}`);
  invoke(
    deployed.SHIPMENT,
    "initialize",
    `--identity_contract ${deployed.IDENTITY} --reputation_contract ${deployed.REPUTATION} --escrow_contract ${deployed.ESCROW} --document_contract ${deployed.DOCUMENT}`
  );

  console.log(`\nAll contracts deployed. IDs written to ${ENV_OUT}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
